[FEAT] Create <Class /> utility component
DavidHDev/react-haiku pull request #78
Opened 2024-08-13 23:53 UTC by pushpendersingh97

Description:
Implement a utility component, , that simplifies adding or removing CSS classes dynamically in a React application.

Acceptance Criteria:
- [ ] The component should accept a className prop and apply the corresponding CSS class to the rendered element.
- [ ]  It should provide additional props or functions to conditionally add or remove classes based on specific conditions.

2024-08-13 23:55 UTC, pushpendersingh97 commented
Hi @DavidHDev 
I tried to run this locally, but I am unable to do the same. I am facing the same issue as @francoisdillinger faced. Please help where I am doing wrong. 

![Screenshot 2024-08-14 at 5 25 35 AM](https://github.com/user-attachments/assets/6d67f8d7-8087-4200-97db-038e3d4bdafd)

2024-08-14 04:06 UTC, DavidHDev requested changes

2024-08-14 04:06 UTC, DavidHDev commented on lib/utils/Class.tsx
> +  children,
It would be useful to have an `"as"` prop as well. So that the user can render the Class as different HTML tags, like `p`, `a`, `span`, etc. Because there are cases when you don't want this parent element to be a div

It would look something like this:

```jsx
<Class 
  className="base-class"
  condition={isActive}
  toggleClass="active-class"
  as="a" // makes this wrapper a link
  
  // user can add any other html attributes
  href="https://google.com/"
>
  This is a link!
</Class>
```

Here's a suggestion for the updated code:

```jsx
import React, { ReactNode, ElementType } from "react";

interface ClassProps {
  className?: string;
  condition?: boolean;
  toggleClass?: string;
  children: ReactNode;
  as?: ElementType; // Add the "as" prop to allow dynamic element types
  [key: string]: any; // Allow other arbitrary props like `href`, `onClick`, etc.
}

/**
 * Class component that conditionally applies a class name to a specified HTML element.
 *
 * @param className - The initial class name for the element.
 * @param condition - The condition to determine whether to apply the toggle class or not.
 * @param toggleClass - The class name to be toggled based on the condition.
 * @param children - The content to be rendered inside the specified HTML element.
 * @param as - The type of HTML element to render.
 * @param props - Any additional props to be passed to the element.
 * @returns The rendered Class component.
 */
export const Class: React.FC<ClassProps> = ({
  className = "",
  condition = false,
  toggleClass = "",
  children,
  as: Component = "div", // Default to "div" if no "as" prop is provided
  ...props // Spread the rest of the props to the rendered element
}) => {
  const computedClassName = condition
    ? `${className} ${toggleClass}`.trim()
    : className;

  return (
    <Component className={computedClassName} {...props}>
      {children}
    </Component>
  );
};
```

This option should be added to the docs as well

2024-08-14 04:06 UTC, DavidHDev commented on docs/docs/utilities/class.mdx
> +export const ClassDemo = () => {
This should be named `export const Component` for simplicity, all the other pages do the same

2024-08-14 04:06 UTC, DavidHDev commented on docs/demo/ClassDemo.jsx
> +      </button>
Pleae add some `margin-bottom` to this so that the text below has some space between it and the button.

2024-08-14 04:06 UTC, DavidHDev commented
Hi @pushpendersingh97 , again this is because the component imported from 'react-haiku' is not part of the package release yet (since you just created it), so of course it would not work locally, unless you manually link the local version of the library using `npm link`, with the steps written in CONTRIBUTING.MD:

1. In the `root` folder of the repo:
- `npm run build` to build the hook library locally
- `npm link` to link the local version of the library to your global environment

2. In the `docs` folder:
- Delete the existing `react-haiku` folder from the `node_modules` directory
- `npm link react-haiku` to activate the link with the local version of the library
- Now you can check the linked `react-haiku` package in the `node_modules` directory (it should have a little arrow to the right of the package name) and see that it includes the hooks/utilities that are not yet released.

2024-08-16 06:27 UTC, pushpendersingh97 commented
Working on Code Review comments.

2024-08-17 10:32 UTC, pushpendersingh97 commented on docs/demo/ClassDemo.jsx
> +
Done

2024-08-17 10:32 UTC, pushpendersingh97 commented
Hi @DavidHDev 
I am done with the code review comments, Please check once.

2024-08-18 15:01 UTC, DavidHDev approved these changes

2024-08-18 15:03 UTC, DavidHDev commented
Thanks! I will merge this the following days when I have time to do a release! 👍

2024-08-23 13:23 UTC, pushpendersingh97 commented
@DavidHDev  By when this will be live?

2024-08-23 18:50 UTC, merged

2024-08-23 19:00 UTC, DavidHDev commented
Hi @pushpendersingh97 ! Just did a release with it:
https://www.reacthaiku.dev/docs/utilities/class