Feature/use cookie
DavidHDev/react-haiku pull request #9
Opened 2022-08-16 17:49 UTC by nicofrem

Hi!

I added two new hooks.

**useCookieListener**: This hook is a  listen for cookies  when they change their value.
- The first parameter is a function with the cookie value and cookie key that was modified (from devtool or other cookie setter)
- The second parameter is an array of strings with cookie dependencies. This parameter is optional. If you don't pass something this hook is listening all cookies

Listening `my-cookie` and `my-cookie-2`
````
useCookieListener((cookieValue, cookieKey) => {
    console.log(cookieValue, cookieKey);
}, ['my-cookie', 'my-cookie-2');
````
Listening all cookies
````
useCookieListener((cookieValue, cookieKey) => {
    console.log(cookieValue, cookieKey);
});
````

**useCookie**: this is a hook similar to useState and useLocalStorage but his value is storaged on browser cookie.

- The first parameter is a string with the cookie key.
- The second parameter is optional with the initial value.
- The third parameter is optional with the expiration days of the cookie.

Simple use
````
const [myCookie, setMyCookie] = useCookie('my-cookie');
````
Full use
````
const [myCookie, setMyCookie, deleteMyCookie] = useCookie('my-cookie', { lorem: "ipsum" }, 100);
````

**These hooks were tested on Google Chrome**

2022-08-17 21:46 UTC, m10rten requested changes

2022-08-17 21:46 UTC, m10rten commented on lib/helpers/cookie.js
> +    return value === 'undefined' ? undefined : JSON.parse(value ?? '');
JSON.parse on an empty string will result in errors.
make it {} or [] instead.

2022-08-17 21:46 UTC, m10rten commented on lib/helpers/cookie.js
> +  return JSON.stringify(value);
nullish check wouldnt be to bad, pretty much only check if its a string or not.

2022-08-17 21:46 UTC, m10rten commented on lib/helpers/cookie.js
> +  const [, cookie] = value.split(`; ${name}=`);
`[, cookie]` the `,` will result in errors if you dont put a _ `variableName` or `_` in front of it.

2022-08-17 21:46 UTC, m10rten commented on lib/helpers/cookie.js
> +  date.setTime(date.getTime() + expireDays * 24 * 60 * 60 * 1000);
you should make this string a const, easier to read in my opinion.

2022-08-26 23:17 UTC, nicofrem commented on lib/helpers/cookie.js
> +  return JSON.stringify(value);
This case is because I need to return the string value without double quotes. The `JSON.stringify` adds double quotes to the string value.
When the value is `undefined`, `JSON.stringify` returns `undefined`, so I don't need to check if the value is `undefined`


```
const stringValue = "Lorem ipsum";
const undefinedValue = undefined;

JSON.stringify(stringValue) // '"Lorem ipsum"'
JSON.stringify(undefinedValue) // undefined
```

2022-08-27 07:46 UTC, m10rten approved these changes
Looks solid mate🚀

2022-08-27 14:07 UTC, DavidHDev approved these changes
Thank you for the contribution and for resolving the comments, I will handle updating the docs when the new release will come out :)

2022-08-27 14:08 UTC, merged